### ISSUE TITLE
Selected token sets not recalled

### ISSUE THREAD

**Issue by engegu** [six7/figma-tokens#566] opened 2022-03-30 11:37 UTC
The plugin does not remember which token sets was selected when i last used it, nescessating a re-enable of anything other than the first set every time i start the plugin. This is mostly an annoyance but a fix would be great.

**Comment by six7** [comment] 2022-03-30 22:35
Closing this as it's a duplicate of #534 - will hopefully tackle this soon! 🙏

**Closed** 2022-03-30 22:35 UTC
