### ISSUE TITLE
Referencing a typography token to another as value

### ISSUE THREAD

**Issue by ahhauhhu** [six7/figma-tokens#602] opened 2022-04-13 07:31 UTC
**Is your feature request related to a problem? Please describe.**
Our typography library is built with global and alias tokens. 
- Global tokens, e.g. f100, f200, contain values with properties like fontSize, fontFamily, fontWeight... 
- Alias tokens, e.g. ui_text.normal, ui_text.large, make references to the global ones and are meant for specific use cases.

The plugin currently support this type of structure in JSON files, but the tokens themselves have no effects when applied to text layers in Figma. Also styles created from these tokens don't match the referenced properties.

**Describe the solution you'd like**
It would be helpful if the plugin could support having typography tokens referencing one another. This means when creating styles in Figma from tokens with references, the styles reflect exactly the referenced properties

**Describe alternatives you've considered**
I tried having the alias tokens referencing properties in the global tokens, instead of the tokens themselves. For example, the fontWeight of token "ui_text.normal" is global.tokens.f100.fontWeight. But this didn't work. When I apply the token "ui_text.normal" to a text layer, or create style from it, it has no effects.

**Additional context**
screenshot of a global token set
<img width="395" alt="image" src="https://user-images.githubusercontent.com/30395676/163123429-048ecca6-c5ff-4788-bfa8-86d190f886d0.png">

screenshot of an alias token set
<img width="391" alt="image" src="https://user-images.githubusercontent.com/30395676/163123480-e601b19b-d502-4c8e-b799-3ebbb15e1119.png">

screenshot of a global token referencing an alias token
<img width="238" alt="image" src="https://user-images.githubusercontent.com/30395676/163146343-0aad02db-69dd-49c7-86e5-0cba7eb1f35b.png">

screenshot of a global token referencing properties of an alias token
<img width="241" alt="image" src="https://user-images.githubusercontent.com/30395676/163146517-fd57854c-25f9-41f5-a69f-b0d8aae6829c.png">

**Comment by jam-awake** [comment] 2022-04-13 19:28
Is this a duplicate of https://github.com/six7/figma-tokens/issues/457?

**Comment by six7** [comment] 2022-04-23 22:33
> Is this a duplicate of https://github.com/six7/figma-tokens/issues/457?

Not a duplicate, this one is more about being able to reference a whole typography token in another one.

Both are coming soon 👍

**Comment by ahhauhhu** [comment] 2022-04-26 07:25
looking forward to the update! Let me know if you need any clarification on use cases.

**Comment by six7** [comment] 2022-04-28 21:19
Re-reading this issue it seems you're describing something that works since a long time, your aliases just are set up incorrectly.

Remove the 'global' from your aliases (the first part), then it already works.

What we'll be shipping is the ability to reference a whole typography token to another one.

Closing this one, as it's functionality is already in the plugin. Feel free to reopen if I was wrong 🙏

**Closed** 2022-04-28 21:20 UTC
