### ISSUE TITLE
Show layers using a certain token on Multi-Inspector

### ISSUE THREAD

**Issue by tarikhaiga** [six7/figma-tokens#538] opened 2022-03-18 20:24 UTC
**Is your feature request related to a problem? Please describe.**

🟡 The problem is being able to identify the layers where undesired tokens are applied, especially in a frame that has many UI components and tokens used. We can already see the number of layers to which a token is applied to, and I believe thru Figma API we can get the names of those layers too.

**Describe the solution you'd like**
🟡 Under the Inspect feature, the user is able to use the Multi-Inspector in order to view the layers (e.g. names of layers) using a certain token.

**Describe alternatives you've considered**
🟡 I currently manually have to guess where broken tokens are applied. Could not figure out a quick way to automatte things.

**Additional context**

A simple & quick solution can be a tooltip/dialog box that shows up a list of layers' names using that broken color.bg.disabled.

<img width="419" alt="token-feature-req" src="https://user-images.githubusercontent.com/13916243/159077862-dfdf6937-f7a2-4e7c-8add-bf045b8e6902.png">

**Comment by six7** [comment] 2022-03-19 14:25
I think this is a duplicate of https://github.com/six7/figma-tokens/issues/513

If you agree, let's close this one?

**Comment by tarikhaiga** [comment] 2022-03-19 17:38
Yes I agree, let's close this one. Thanks Jan!

**Closed** 2022-03-19 17:39 UTC
