### ISSUE TITLE
Can't create new tokens when using a second access token with Github sync

### ISSUE THREAD

**Issue by iamnbutler** [six7/figma-tokens#479] opened 2022-02-21 20:55 UTC
**Describe the bug**
This is a bit of a weird one, I'll try to clarify the issue once I understand the expected way this is supposed to work.

I'm having an issue with my team where when we have multiple people using Figma Tokens with GitHub sync: One of the editors can't make tokens, but only if they use their own personal access token. They have read access all tokens, but can't create new ones.

We were able to resolve this by having the second editor use my access token instead.

Is it intended that a single access token should be used to sync with GitHub? I looked through all the open issues and the documentation but didn't see a mention of this.

---

Things I checked before reporting:

Second editor has:

- Manage access to the repo
- Editor access in Figma
- A fresh access token with repo access
- Cleared figma cache, tried both desktop and web, on multiple machines

**To Reproduce**

1. Create figma file with multiple editors
2. Add tokens to file
3. Creator turns on token sync using GitHub and sets up with their credentials
4. Second editor sets up token sync using their own personal access token
5. Second editor cannot create new tokens (clicking the `[+]` in the UI does nothing.)

**Expected behavior**

I'd expect each contributor to use their own access token so that the commit history accurately reflects who made the changes, etc.

**JSON (optional)**
Probably not relevant, but will include JSON anyways:

```
{
  "core": {
    "color": {
      "neutral": {
        "0": {
          "value": "#ffffff",
          "type": "color"
        },
        "50": {
          "value": "#f8f8f8",
          "type": "color"
        },
        "100": {
          "value": "#f0f0f0",
          "type": "color"
        },
        "150": {
          "value": "#e1e1e1",
          "type": "color"
        },
        "200": {
          "value": "#d2d2d2",
          "type": "color"
        },
        "250": {
          "value": "#c3c3c3",
          "type": "color"
        },
        "300": {
          "value": "#b4b4b4",
          "type": "color"
        },
        "350": {
          "value": "#a5a5a5",
          "type": "color"
        },
        "400": {
          "value": "#969696",
          "type": "color"
        },
        "450": {
          "value": "#878787",
          "type": "color"
        },
        "500": {
          "value": "#787878",
          "type": "color"
        },
        "550": {
          "value": "#696969",
          "type": "color"
        },
        "600": {
          "value": "#5a5a5a",
          "type": "color"
        },
        "650": {
          "value": "#4b4b4b",
          "type": "color"
        },
        "700": {
          "value": "#3c3c3c",
          "type": "color"
        },
        "750": {
          "value": "#262626",
          "type": "color"
        },
        "800": {
          "value": "#1e1e1e",
          "type": "color"
        },
        "850": {
          "value": "#0f0f0f",
          "type": "color"
        },
        "900": {
          "value": "#000000",
          "type": "color"
        }
      },
      "steel": {
        "0": {
          "value": "#F8FAFC",
          "type": "color"
        }
      },
      "gray": {
        "0": {
          "value": "#F9FAFB",
          "type": "color"
        }
      },
      "rose": {
        "0": {
          "value": "#FFF1F2",
          "type": "color"
        }
      },
      "red": {
        "0": {
          "value": "#FEF2F2",
          "type": "color"
        },
        "100": {
          "value": "#FEE2E2",
          "type": "color"
        },
        "200": {
          "value": "#FECACA",
          "type": "color"
        },
        "300": {
          "value": "#FCA5A5",
          "type": "color"
        },
        "400": {
          "value": "#F87171",
          "type": "color"
        },
        "500": {
          "value": "#EF4444",
          "type": "color"
        },
        "600": {
          "value": "#DC2626",
          "type": "color"
        },
        "700": {
          "value": "#B91C1C",
          "type": "color"
        },
        "800": {
          "value": "#991B1B",
          "type": "color"
        },
        "900": {
          "value": "#7F1D1D",
          "type": "color"
        }
      },
      "orange": {
        "0": {
          "value": "#FFF7ED",
          "type": "color"
        }
      },
      "amber": {
        "0": {
          "value": "#FFFBEB",
          "type": "color"
        }
      },
      "yellow": {
        "0": {
          "value": "#FEFCE8",
          "type": "color"
        }
      },
      "lime": {
        "0": {
          "value": "#F7FEE7",
          "type": "color"
        }
      },
      "green": {
        "0": {
          "value": "#F0FDF4",
          "type": "color"
        }
      },
      "emerald": {
        "0": {
          "value": "#ECFDF5",
          "type": "color"
        }
      },
      "teal": {
        "0": {
          "value": "#F0FDFA",
          "type": "color"
        }
      },
      "cyan": {
        "0": {
          "value": "#ECFEFF",
          "type": "color"
        }
      },
      "sky": {
        "0": {
          "value": "#F0F9FF",
          "type": "color"
        }
      },
      "blue": {
        "0": {
          "value": "#EFF6FF",
          "type": "color"
        }
      },
      "indigo": {
        "0": {
          "value": "#EEF2FF",
          "type": "color"
        }
      },
      "violet": {
        "0": {
          "value": "#F5F3FF",
          "type": "color"
        }
      },
      "purple": {
        "0": {
          "value": "#FAF5FF",
          "type": "color"
        }
      },
      "fuschia": {
        "0": {
          "value": "#FDF4FF",
          "type": "color"
        }
      },
      "pink": {
        "0": {
          "value": "#FDF2F8",
          "type": "color"
        }
      }
    },
    "text": {
      "family": {
        "zed-mono": {
          "value": "Zed Mono",
          "type": "fontFamilies"
        },
        "zed-sans": {
          "value": "Zed Sans",
          "type": "fontFamilies"
        }
      },
      "size": {
        "xs": {
          "value": "12",
          "type": "fontSizes"
        },
        "sm": {
          "value": "14",
          "type": "fontSizes"
        },
        "base": {
          "value": "16",
          "type": "fontSizes"
        },
        "lg": {
          "value": "18",
          "type": "fontSizes"
        },
        "xl": {
          "value": "20",
          "type": "fontSizes"
        }
      },
      "leading": {
        "xs": {
          "value": "12",
          "type": "lineHeights"
        },
        "sm": {
          "value": "14",
          "type": "lineHeights"
        },
        "base": {
          "value": "16",
          "type": "lineHeights"
        },
        "lg": {
          "value": "18",
          "type": "lineHeights"
        },
        "xl": {
          "value": "20",
          "type": "lineHeights"
        },
        "2xl": {
          "value": "22",
          "type": "lineHeights"
        }
      },
      "weight": {
        "normal": {
          "value": "Regular",
          "type": "fontWeights"
        },
        "bold": {
          "value": "Bold",
          "type": "fontWeights"
        }
      },
      "tracking": {
        "default": {
          "value": "0%",
          "type": "letterSpacing"
        }
      },
      "paragraphSpacing": {
        "0": {
          "value": "0",
          "type": "paragraphSpacing"
        }
      },
      "case": {
        "default": {
          "value": "none",
          "type": "textCase"
        }
      },
      "decoration": {
        "none": {
          "value": "none",
          "type": "textDecoration"
        }
      },
      "ui": {
        "base": {
          "value": {
            "fontFamily": "$text.family.zed-sans",
            "fontWeight": "$text.weight.normal",
            "lineHeight": "$text.leading.base",
            "fontSize": "$text.size.xs",
            "letterSpacing": "$text.tracking.default",
            "paragraphSpacing": "$text.paragraphSpacing.0",
            "textCase": "$text.case.default",
            "decoration": "$text.decoration.none",
            "textDecoration": "$text.decoration.none"
          },
          "type": "typography",
          "bold": {
            "value": {
              "fontFamily": "$text.family.zed-sans",
              "fontWeight": "$text.weight.bold",
              "lineHeight": "$text.leading.base",
              "fontSize": "$text.size.xs",
              "letterSpacing": "$text.tracking.default",
              "paragraphSpacing": "$text.paragraphSpacing.0",
              "textCase": "$text.case.default",
              "decoration": "$text.decoration.none",
              "textDecoration": "$text.decoration.none"
            },
            "type": "typography"
          }
        },
        "base-bold": {
          "value": {
            "fontFamily": "$text.family.zed-sans",
            "fontWeight": "$text.weight.bold",
            "lineHeight": "$text.leading.base",
            "fontSize": "$text.size.xs",
            "letterSpacing": "$text.tracking.default",
            "paragraphSpacing": "$text.paragraphSpacing.0",
            "textCase": "$text.case.default",
            "decoration": "$text.decoration.none",
            "textDecoration": "$text.decoration.none"
          },
          "type": "typography"
        }
      },
      "buffer": {
        "sm": {
          "value": {
            "fontFamily": "$text.family.zed-mono",
            "fontWeight": "$text.weight.normal",
            "lineHeight": "$text.leading.base",
            "fontSize": "$text.size.xs",
            "letterSpacing": "$text.tracking.default",
            "paragraphSpacing": "$text.paragraphSpacing.0",
            "textCase": "$text.case.default",
            "decoration": "$text.decoration.none",
            "textDecoration": "$text.decoration.none"
          },
          "type": "typography"
        },
        "base": {
          "value": {
            "fontFamily": "$text.family.zed-mono",
            "fontWeight": "$text.weight.normal",
            "lineHeight": "$text.leading.2xl",
            "fontSize": "$text.size.sm",
            "letterSpacing": "$text.tracking.default",
            "paragraphSpacing": "$text.paragraphSpacing.0",
            "textCase": "$text.case.default",
            "decoration": "$text.decoration.none"
          },
          "type": "typography"
        }
      }
    },
    "space": {
      "w-4": {
        "value": "$base",
        "type": "spacing"
      },
      "w-8": {
        "value": "$base * 2",
        "type": "spacing"
      },
      "w-12": {
        "value": "$base * 3",
        "type": "spacing"
      },
      "w-16": {
        "value": "$base * 4",
        "type": "spacing"
      }
    },
    "base": {
      "value": "4",
      "type": "spacing"
    }
  },
  "base": {
    "color": {
      "semantic": {
        "alert": {
          "value": "$color.red.500",
          "type": "color"
        },
        "warning": {
          "value": "#FDE047",
          "type": "color"
        },
        "info": {
          "value": "#3B82F6",
          "type": "color"
        },
        "positive": {
          "value": "#4FAC63",
          "type": "color"
        },
        "collaborator": {
          "teal": {
            "value": "#2DD4BF",
            "type": "color"
          },
          "green": {
            "value": "#A3E635",
            "type": "color"
          },
          "purple": {
            "value": "#7C3AED",
            "type": "color"
          },
          "blue": {
            "value": "#3B82F6",
            "type": "color"
          }
        }
      },
      "system": {
        "mac-os": {
          "red": {
            "value": "#FF5E57",
            "type": "color"
          },
          "yellow": {
            "value": "#FFBB2E",
            "type": "color"
          },
          "green": {
            "value": "#38C149",
            "type": "color"
          }
        }
      }
    },
    "buffer": {
      "highlight": {
        "active": {
          "value": "$",
          "type": "color"
        },
        "folded": {
          "value": "$",
          "type": "color"
        },
        "match": {
          "value": "$",
          "type": "color"
        },
        "active-match": {
          "value": "$",
          "type": "color"
        },
        "diff-minus": {
          "value": "$",
          "type": "color"
        },
        "diff-add": {
          "value": "$",
          "type": "color"
        }
      },
      "fold-lines": {
        "value": "$",
        "type": "color"
      }
    }
  },
  "dark": {
    "text": {
      "active": {
        "value": "$color.neutral.0",
        "type": "color"
      },
      "default": {
        "value": "$color.neutral.100",
        "type": "color"
      },
      "secondary": {
        "value": "$color.neutral.350",
        "type": "color"
      },
      "muted": {
        "value": "$color.neutral.550",
        "type": "color"
      },
      "inactive": {
        "value": "$color.neutral.650",
        "type": "color"
      },
      "minimal": {
        "value": "$color.neutral.750",
        "type": "color"
      },
      "semantic": {
        "error": {
          "value": "#E06C75",
          "type": "color"
        },
        "warning": {
          "value": "#D1B366",
          "type": "color"
        }
      }
    },
    "surface": {
      "100": {
        "value": "$color.neutral.750",
        "type": "color"
      },
      "300": {
        "value": "$color.neutral.800",
        "type": "color"
      },
      "400": {
        "value": "$color.neutral.850",
        "type": "color"
      },
      "500": {
        "value": "$color.neutral.900",
        "type": "color"
      }
    },
    "border": {
      "default": {
        "value": "$color.neutral.850",
        "type": "color"
      },
      "muted": {
        "value": "$color.neutral.700",
        "type": "color"
      },
      "active": {
        "value": "$color.neutral.500",
        "type": "color"
      }
    },
    "icon": {
      "active": {
        "value": "$text.active",
        "type": "color"
      },
      "secondary": {
        "value": "$text.secondary",
        "type": "color"
      },
      "muted": {
        "value": "$text.muted",
        "type": "color"
      },
      "inactive": {
        "value": "$text.inactive",
        "type": "color"
      }
    },
    "syntax": {
      "color": {
        "primary": {
          "value": "$text.default",
          "type": "color"
        },
        "constant": {
          "value": "$syntax.color.primary",
          "type": "color"
        },
        "comment": {
          "value": "$text.muted",
          "type": "color"
        },
        "predictive": {
          "value": "$text.muted",
          "type": "color"
        },
        "punctuation": {
          "value": "$text.secondary",
          "type": "color"
        },
        "keyword": {
          "value": "#7DD3FC",
          "type": "color"
        },
        "function": {
          "value": "#FDE68A",
          "type": "color"
        },
        "string": {
          "value": "#818CF8",
          "type": "color"
        },
        "type": {
          "value": "#6EE7B7",
          "type": "color"
        },
        "variant": {
          "value": "$syntax.color.type",
          "type": "color"
        },
        "number": {
          "value": "#FBBF24",
          "type": "color"
        },
        "boolean": {
          "value": "$syntax.color.number",
          "type": "color"
        },
        "property": {
          "value": "$syntax.color.keyword",
          "type": "color"
        },
        "operator": {
          "value": "#E879F9",
          "type": "color"
        },
        "enum": {
          "value": "$syntax.color.operator",
          "type": "color"
        }
      },
      "buffer": {
        "bg": {
          "value": "$surface.500",
          "type": "color"
        },
        "selection": {
          "value": "#FFFFFF14",
          "type": "color"
        }
      },
      "gutter": {
        "active": {
          "value": "$text.active",
          "type": "color"
        },
        "inactive": {
          "value": "$text.muted",
          "type": "color"
        }
      }
    }
  },
  "light": {
    "text": {
      "active": {
        "value": "$color.neutral.900",
        "type": "color"
      },
      "default": {
        "value": "$color.neutral.800",
        "type": "color"
      },
      "secondary": {
        "value": "$color.neutral.600",
        "type": "color"
      },
      "muted": {
        "value": "$color.neutral.500",
        "type": "color"
      },
      "inactive": {
        "value": "$color.neutral.300",
        "type": "color"
      },
      "minimal": {
        "value": "$color.neutral.150",
        "type": "color"
      },
      "semantic": {
        "error": {
          "value": "#E06C75",
          "type": "color"
        },
        "warning": {
          "value": "#D1B366",
          "type": "color"
        }
      }
    },
    "surface": {
      "100": {
        "value": "$color.neutral.250",
        "type": "color"
      },
      "300": {
        "value": "$color.neutral.150",
        "type": "color"
      },
      "400": {
        "value": "$color.neutral.100",
        "type": "color"
      },
      "500": {
        "value": "$color.neutral.50",
        "type": "color"
      }
    },
    "border": {
      "default": {
        "value": "$color.neutral.300",
        "type": "color"
      },
      "muted": {
        "value": "$color.neutral.200",
        "type": "color"
      },
      "active": {
        "value": "$color.neutral.300",
        "type": "color"
      }
    },
    "icon": {
      "active": {
        "value": "$text.active",
        "type": "color"
      },
      "secondary": {
        "value": "$text.secondary",
        "type": "color"
      },
      "muted": {
        "value": "$text.muted",
        "type": "color"
      },
      "inactive": {
        "value": "$text.inactive",
        "type": "color"
      }
    },
    "syntax": {
      "color": {
        "primary": {
          "value": "$text.default",
          "type": "color"
        },
        "constant": {
          "value": "$syntax.color.primary",
          "type": "color"
        },
        "comment": {
          "value": "$text.muted",
          "type": "color"
        },
        "predictive": {
          "value": "$text.muted",
          "type": "color"
        },
        "punctuation": {
          "value": "$text.secondary",
          "type": "color"
        },
        "keyword": {
          "value": "#7DD3FC",
          "type": "color"
        },
        "function": {
          "value": "#FDE68A",
          "type": "color"
        },
        "string": {
          "value": "#818CF8",
          "type": "color"
        },
        "type": {
          "value": "#6EE7B7",
          "type": "color"
        },
        "variant": {
          "value": "$syntax.color.type",
          "type": "color"
        },
        "number": {
          "value": "#FBBF24",
          "type": "color"
        },
        "boolean": {
          "value": "$syntax.color.number",
          "type": "color"
        },
        "property": {
          "value": "$syntax.color.keyword",
          "type": "color"
        },
        "operator": {
          "value": "#E879F9",
          "type": "color"
        },
        "enum": {
          "value": "$syntax.color.operator",
          "type": "color"
        }
      },
      "buffer": {
        "bg": {
          "value": "$surface.500",
          "type": "color"
        },
        "selection": {
          "value": "#0000000A",
          "type": "color"
        }
      },
      "gutter": {
        "active": {
          "value": "$text.active",
          "type": "color"
        },
        "inactive": {
          "value": "$text.muted",
          "type": "color"
        }
      }
    }
  }
}
```

**Comment by six7** [comment] 2022-02-22 07:12
Are you sure the second access token has write scope defined and has access to that repository? It reads like it only has read scope defined.

**Comment by jakobe** [comment] 2022-03-02 14:18
I just checked this with my colleague and it works as intended, we can both pull from and push to our GitHub repo using our own access token (2 different ones, that is).

@iamnbutler My guess is your second token only has read access or if you're in an org repo you forgot to SSO enable the second token (happens a lot in our org 😄 )

**Comment by jakobe** [comment] 2022-03-02 14:58
Hey @iamnbutler ,
Sorry, maybe I was to quick 🙈 
I see now according to your "steps to reproduce", that it might not be a GitHub sync issue, but more related to the UI in the plugin as such.

I did try to reproduce your issue, and while I _can_ create a new token it can end up at the bottom if I have "top-level" tokens as well as nested ones.

Maybe this screenshot describes it better:
* If I add a new token to "gray" using the `+` icon it ends up at the end of "gray" (the green circle)
* If I add a new token to the top level "color" (also using the `+` icon) it ends up at the end of the entire "color" group and after "gray" (the red circle)
![image](https://user-images.githubusercontent.com/9556693/156386387-b97dd469-a34e-4487-ad72-957c5ea4b3bf.png)

Is your issue similar or something else?

**Comment by iamnbutler** [comment] 2022-03-02 16:18
Ok great! Let me to some more through testing, and ensure we aren't having read only issues.

> My guess is your second token only has read access or if you're in an org repo you forgot to SSO enable the second token (happens a lot in our org 😄 )

Oh, I don't think I've checked this. It could be the issue. Will report back!

> Is your issue similar or something else?

I'll check following your steps to see if I have the same issue once resolving the above!

**Comment by six7** [comment] 2022-03-06 08:33
Were you able to resolve this @iamnbutler ? Let me know if there's anything I can do to help! 🙏

**Comment by iamnbutler** [comment] 2022-03-07 15:28
Been a bit slammed but will test this in the afternoon and see if we can't resolved!

**Comment by iamnbutler** [comment] 2022-03-15 00:06
So we spent some time on this, I'm not sure which of the things we did fixed it but my co-worker was able to write tokens after manually adding him to the repo with write access (even though he should have already had write access from the org-level settings.)

**Comment by mtopping** [comment] 2022-08-09 18:14
As @iamnbutler found, this has solved the same issue for our team in Gitlab.

We had two team members with `owner` permissions for the repo inherited from their org/team association.

We went into the project this repo belonged to and explicitly added them again (they will show up twice in the members list) as a "Direct Member." They are now able to access, pull, push, write using personal access tokens.

Thank you!

**Comment by six7** [comment] 2022-11-03 20:08
Closing this since it seems to have been solved.

**Closed by six7** 2022-11-03 20:08 UTC
