### ISSUE TITLE
Export/Sync settings: Transform aliases into values

### ISSUE THREAD

**Issue by alexhris** [six7/figma-tokens#531] opened 2022-03-17 16:25 UTC
1) Some frontend libraries, like Chakra UI, accept full json files as a way to override their native styles (their own tokens). Hence, we cannot use aliases defined in one json block to another because we don't convert them to js variables. For example a Typography style that references a Font-size token is unusable.

`  "heading-lg": {
    "value": {
      "fontFamily": "$fontFamilies.inter",
      "fontWeight": "$fontWeights.inter-1",
      "lineHeight": "$lineHeights.5",
      "fontSize": "$fontSize.5",
      "letterSpacing": "$letterSpacing.6",
      "paragraphSpacing": "$paragraphSpacing.0",
      "textCase": "$textCase.none",
      "textDecoration": "$textDecoration.none"
    },
    "type": "typography",
    "description": "1.75rem"
  },`

It would be great if I can just check "Use values instead of aliases / Convert aliases into values" while exporting or pushing to GitHub as a setting.

Bonus: Adding a field for "rem" values for each "px" property (even if it's just a description field) would be a great facilitator!

Thanks!

**Comment by six7** [comment] 2022-03-30 22:43
This should fit in nicely with the resolve tokens option for the transformer 👍 will hopefully get to this soon! 🙏

**Comment by alexhris** [comment] 2022-04-08 09:05
Awesome! Thanks a lot :)

**Comment by six7** [comment] 2022-05-19 18:13
Closing this in favor of https://github.com/six7/figma-tokens/issues/423

Duplicate of #423

**Closed by six7** 2022-05-19 18:13 UTC
