### ISSUE TITLE
Renaming styles not working without using themes.

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1377] opened 2022-10-25 08:28 UTC
**Describe the bug**
Since 123, you can rename tokens and the plugin asks to rename the styles as well. This is working when you're working with themes, but when you're not using themes, the style doesn't get renamed. Also if you afterwards change a color for example, this is not updated.

Introduced after release 123

**To Reproduce**
Steps to reproduce in the attached video.

**Expected behavior**
Would expect that the style gets renamed and also the style updates afterwards, if for example the color is changed.

**Note**
Some strange behaviour when you first create the style without themes and afterwards create styles with a theme for the same token. In this case the plugin and style seems to be messed up, which causes the renaming not to work within themes as well.

**Screenshots or Screencasts**
https://user-images.githubusercontent.com/109062656/197723344-cf5cf5a7-11e0-4326-b0d7-bf9c9bdae7e4.mp4

Related issue: https://github.com/six7/figma-tokens/issues/1194

**Comment by six7** [comment] 2022-11-01 22:47
Closing this as it seems to be a duplicate of #1194

**Closed** 2022-11-01 22:46 UTC
Labels: bug
