### ISSUE TITLE
Allow to specificy token "type" when creating an "other" token

### ISSUE THREAD

**Issue by sir-captainmorgan21** [six7/figma-tokens#1186] opened 2022-08-18 02:51 UTC
**Is your feature request related to a problem? Please describe.**
When we define "other" token types (IE: Screens), we cant easily use Style Dictionary to filter out tokens to translate with. It is possible, but it would be nice to be able to specify the type of token thatll show up in the json output.

**Describe the solution you'd like**
When exporting "other" types, the json output should be something like...
Right now its looks like this:
```
...
"Desktop": {
   "value": "1280px",
   "type": "other"
}
...
```
We cant do much with "other". What if we have many sets of "other" types.
Instead it would be nice to provide the type the token is under and result in:
```
...
"Desktop": {
   "value": "1280px",
   "type": "mycustomtype"
}
...
```

**Describe alternatives you've considered**
A work around for now is creating filter function in style dictionary that filters the token out by its parent in the path for now.

**Additional context**
Nothing more to add here

**Comment by six7** [comment] 2022-08-19 18:54
You can do what you described in the JSON, but there's currently no way in the UI to do that. 

This sounds like a duplicate of https://github.com/six7/figma-tokens/issues/650 - should we use that one to track that work?

**Closed** 2022-08-21 01:09 UTC
