### ISSUE TITLE
Ability to reorder the token sets and within the token list item

### ISSUE THREAD

**Issue by guyenner** [six7/figma-tokens#509] opened 2022-03-08 17:09 UTC
**Is your feature request related to a problem? Please describe.**
Currently, when you add a new color token in a color token list, it automatically is added at the end of the queue. When I add a new set of tokens due to product/ design need, for example quaternary colors, I would like to be able to reorder it so it sits right after tertiary colors instead of at the end of the grey color token. Hypothetically, you can do that via json file but the editor view isn't optimal for coding esp with space bar & tabs.

**Describe the solution you'd like**
An ability to reorder the tokens within a parent token, and among other parent tokens. Perhaps just a 3 dots/ click and drag. 

**Describe alternatives you've considered**
Editing JSON file, but we will need to optimize the editor so it has the same functions as some basic editors: code line number, keyboard help etc. 

**Additional context**
Add any other context or screenshots about the feature request here

**Comment by six7** [comment] 2022-03-09 09:08
I think this is a duplicate of https://github.com/six7/figma-tokens/issues/122

OK if I close this in favor of the other one?

**Comment by guyenner** [comment] 2022-03-09 11:58
Sounds good to me.

**Closed** 2022-03-09 12:26 UTC
