### ISSUE TITLE
Re-locating tokens (between folders) in FT

### ISSUE THREAD

**Issue by t-e-lition** [six7/figma-tokens#173] opened 2021-07-14 14:32 UTC
I have accidentally create a token under a category in FT. Now I cant find a way to move it to a different folder/category as I could in Figma without deleting the while folder.. What to do?

![Screenshot 2021-07-14 at 16 26 38](https://user-images.githubusercontent.com/84501353/125640017-c082581b-9ede-4da9-a8a4-ba00491110d8.png)

**Comment by six7** [comment] 2021-07-17 16:05
This issue is a duplicate of #122  — I changed the title over there to make it clearer

**Closed by six7** 2021-07-17 16:05 UTC
