### ISSUE TITLE
Can't Load token file in chrome.

### ISSUE THREAD

**Issue by cfortuner** [six7/figma-tokens#1384] opened 2022-10-26 13:49 UTC
**Describe the bug**

Trying to load token file in google chrome, but it's not allowing me to click it?

WORKS in safari.

**To Reproduce**
1. Open figma token
2. Click Load
3. Click File
4. Click Upload File

**Expected behavior**
Expected to open finder on mac to upload file

**Screenshots or Screencasts**
https://user-images.githubusercontent.com/5430709/198043339-586054eb-6d75-4912-8448-c4aa6391352b.mov

**Comment by rbosker** [comment] 2022-10-26 14:32
@cfortuner are you running the lastest version of Chrome? Just gave this a try at my side and not able to reproduce this behaviour.

**Comment by cfortuner** [comment] 2022-10-27 00:16
whoops. I just noticed I have an update. i'll update and get back to you.

**Comment by six7** [comment] 2022-11-01 22:45
Closing this, please reopen if the issue persists

**Closed** 2022-11-01 22:45 UTC
