### ISSUE TITLE
Applied tokens are not being shown

### ISSUE THREAD

**Issue by Blyawon** [six7/figma-tokens#474] opened 2022-02-19 09:38 UTC
**Describe the bug**
Tokens are applied to a component and visible in the inspect mode. When selecting the component the token is not being shown as active in the component overview.
When I apply the token again it's being "applied" and then shown as active, even though it's been applied before.

**Expected behavior**
Tokens should be shown as applied and active

**Comment by six7** [comment] 2022-02-19 13:53
Duplicate of #470

**Closed by six7** 2022-02-19 13:53 UTC
