### ISSUE TITLE
Deep Inspect - Token remap dropdown not working.

### ISSUE THREAD

**Issue by sakaavee** [six7/figma-tokens#1180] opened 2022-08-17 06:03 UTC
**Describe the bug**
Selected few token and tried to remap those with another token.

Ex. Text.Primary ==> Text.Critical

For the first time dropdown worked fine when trying to remap.

And did the same steps for another token but the dropdown didn't expand. I typed the token name manually to remap.

<img width="599" alt="Screenshot 2022-08-17 at 11 32 06 AM" src="https://user-images.githubusercontent.com/59090839/185046069-e2a442c8-eba6-4658-898c-9bdb56a2f976.png">

**Comment by six7** [comment] 2022-08-17 06:25
Can you tell us what property the token you were trying to remap was applied on?

**Comment by sakaavee** [comment] 2022-08-17 06:31
https://user-images.githubusercontent.com/59090839/185050288-e36d7f2a-2d77-42ab-8c39-1cf3c8860ae2.mov

**Comment by sakaavee** [comment] 2022-08-17 06:32
Only for fill property dropdown is working.

**Comment by six7** [comment] 2022-08-17 07:16
Yes, as I thought. We're tracking work to fix Documentation tokens remap function over in another issue.

Duplicate of #1125 

We have this in our current iteration, should be fixed in one of the upcoming releases.

**Closed by six7** 2022-08-17 07:16 UTC
