### ISSUE TITLE
Allow import of color styles with multiple fills

### ISSUE THREAD

**Issue by sparkpunk** [six7/figma-tokens#403] opened 2022-01-14 19:39 UTC
**Describe the bug**
In Figma projects where there exists multiple children objects (called "folders" in the UI), only the first object ("folder") is imported. For example, on a given project with a "Warning" color family, there are objects/folders called "States" and "Alert" that each have colors nested inside them. When using the "Import" feature using Figma Tokens, only the "States" color styles will be imported.

**To Reproduce**
* Open the Figma MUI component library (free demo [here](https://www.figma.com/community/file/912837788133317724/MUI-for-Figma-v5.0.1-(Free)))
* Open the Figma Tokens plugin, and click "Import"
* Notice how there are tokens missing that are defined in the Styles panel

**Expected behavior**
The expectation is that _all_ defined color styles should be imported, and grouped according to their labels and parent objects.

**Screenshots or Screencasts**
![Figma Tokens & MUI](https://user-images.githubusercontent.com/5074587/149575067-a7ff5781-67ea-4ce3-8ba0-52c9612874c9.jpeg)

**Comment by six7** [comment] 2022-01-17 19:19
The reason for this is that those styles contain more than 1 fill, the plugin so far can only support 1 fill. The main reason blocking me from working on this is: How would multiple fills look like in code? How would we transform this to a css variable?

I'm curious how style dictionary treats tokens with multiple fills (e.g. a color token with an array value: [`#ff00008d`, `#00000050`]

**Comment by sparkpunk** [comment] 2022-01-17 19:28
From what I've seen in another plugin, called [Design Tokens](https://www.figma.com/community/plugin/888356646278934516/Design-Tokens), there's some behind-the-scenes logic that returns the hex value for the combined colors (I'm assuming they're using a library like chroma.js).

**Comment by six7** [comment] 2022-01-17 19:33
Hm, that could work and would only require the one doing the transformation to use this behaviour (e.g. a custom style dictionary transformer).

Theres's another issue: https://github.com/six7/figma-tokens/issues/152 around multiple fills for solids and gradients. So if we'd just keep the value as an array and leave it to the user to transform them according to their needs we could ship this.

Thanks for the suggestion!

**Comment by sparkpunk** [comment] 2022-01-17 20:01
Thanks for all of your hard work on this!

**Comment by six7** [comment] 2022-05-19 18:17
I'll be closing this as a duplicate of https://github.com/six7/figma-tokens/issues/152

**Closed by six7** 2022-05-19 18:17 UTC
Labels: enhancement
