### ISSUE TITLE
Remove token through multi inspect is not working

### ISSUE THREAD

**Issue by esthercheran** [six7/figma-tokens#837] opened 2022-06-08 14:09 UTC
**Describe the bug**
When a token is removed from the inspect tab, the token shows that it is removed. But on restarting the plugin, the removed token is applied again.

**To Reproduce**
1. Apply a token on a layer
2. Go to inspect, remove the applied token. Token is removed.
3. Restart the plugin, inspect the layer.
4. Removed token is applied again

**Expected behavior**
Removed token should be removed even on restarting the plugin

**Screenshots or Screencasts**

Uploading Screen Recording 2022-06-08 at 15.43.42.mov…

**Comment by six7** [comment] 2022-06-08 18:30
Can't reproduce.

**Comment by six7** [comment] 2022-06-09 06:26
Closing this, please reopen if it reappears.

**Closed by six7** 2022-06-09 06:26 UTC
