### ISSUE TITLE
Scoping bug while exporting "Include parent key"

### ISSUE THREAD

**Issue by boyankostov** [six7/figma-tokens#1094] opened 2022-07-28 20:15 UTC
### Describe the bug
I'm not sure that's a bug or intended behaviour, but when I use the export functionality with "Include parent key" enabled, aliases are not scoped correctly or at least not the way style-dictionary would like.  

### To Reproduce
1. Create a reference/alias to an existing color token using the dropdown. The one used here is `neutral.100`
<img width="492" alt="image" src="https://user-images.githubusercontent.com/5939646/181627280-131fd0b4-36e8-4784-9d89-efacc14d1bda.png">
2. Go to export and download the JSON file
3. Use the JSON file with style-dictionary and try to transform to SCSS. An error cause style-dictionary expects `color.neutral.100` rather than `neutral.100`
<img width="602" alt="image" src="https://user-images.githubusercontent.com/5939646/181627239-26f29fb8-9053-48cf-b42d-a4207f95971a.png">
4. If you disable "Include parent key" it works without problems, but you're loosing the group names.

### Expected behavior
Ideally this would get rescoped automatically cause currently I need to either do that manually in Figma or manually in the exported JSON.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/5939646/181628210-192c8440-db1a-41a2-9114-10ff138478f7.png">

Note: I tried searching for a similar issue in the list to no avail. Please excuse me if there's an existing one for the same issue.

**Comment by six7** [comment] 2022-07-30 22:54
This is intended behavior. 114 release will feature a multi file export which is what you'll want.

For now you'd need to split your json manually and feed style dictionary multiple files.

**Comment by six7** [comment] 2022-07-31 00:09
I'm closing this for now, keep an eye on the upcoming 114 which will do what you want.

**Closed by six7** 2022-07-31 00:09 UTC
