### ISSUE TITLE
Persistent variables

### ISSUE THREAD

**Issue by jelle** [six7/figma-tokens#66] opened 2020-12-21 09:48 UTC
Variable references are rendered as hardcoded values when updating the reference token.

Eg:
- reference color token "brand/primary" =  #FF0000
- alias color token "button/primary" = $brand.primary

When the "brand/primary" token is updated, the "button/primary" is no longer linked, the  "$brand.primary" variable gets rendered as "#FF0000".

Any plans to make the variables persistent (even after altering the original token)?

**Comment by six7** [comment] 2020-12-21 12:48
Hey! Hm, that smells like a bug. That's a features that's actually at the core of Figma Tokens, that variables update.

I tried to reproduce it but everything is working as intended, here's my test file: https://www.figma.com/file/K1fU86W9l3htSNBltVPqoR/Tokens-Issue-66-Persistent-variables?node-id=0%3A1

And here a video showing it works. Could you share a file where this issue seems to appear? Or even simpler your Token JSON? Possibly the color references are not set correctly?

![tQDJF25JlB](https://user-images.githubusercontent.com/4548309/102778610-326a1a80-4393-11eb-9f36-37133f0ecc2e.gif)

**Comment by jelle** [comment] 2020-12-21 15:19
Hey, thanks. Great to see that variables can update. Core feature, yes makes sense :)

Indeed it works perfectly when handling everything through the plugin dialog.

I was actually changing my Figma layer styles and then hitting "Import Styles". Obviously this breaks any variable references.

**Comment by six7** [comment] 2020-12-23 13:18
Ah, interesting! I think we can set a description on styles in Figma. I'll add a link when updating styles when theres an alias being used so when you import styles the value of the description can be taken as a value.

e.g. `colors/button` has a description of `$colors.brand.500`

**Comment by jelle** [comment] 2020-12-23 16:18
Nice, would be handy. Thanks!

**Comment by six7** [comment] 2021-05-04 06:26
This is fixed since several versions ago 🙏 Closing this, feel free to reopen

**Closed by six7** 2021-05-04 06:26 UTC
