### ISSUE TITLE
Tokens sorting 

### ISSUE THREAD

**Issue by ibnfahmi** [six7/figma-tokens#406] opened 2022-01-18 11:42 UTC
Sometimes I create a new token that in context are related to one from the beginning of the list, so when this happens, I have to open the json file and copy paste classes to reorder them. 

My suggestion is to have drag and drop sorting ability like how Figma's native styles have.

**Comment by six7** [comment] 2022-01-18 20:00
Definitely needed! I'll close this one as we're already tracking it over in #122 - I think what's described there should match this one.

Duplicate of #122

**Closed by six7** 2022-01-18 20:00 UTC
