### ISSUE TITLE
Optimize the organizational structure of the token set and the token group

### ISSUE THREAD

**Issue by mswbol** [six7/figma-tokens#929] opened 2022-06-24 12:58 UTC
It is hoped that the token set can be grouped to provide multiple nested hierarchical functions in the navigation menu on the left.It is convenient for users to manage and maintain token sets, and the nested token set can be dragged and sorted in the same class.

Please optimize the token group hierarchy shown in the content on the right to make it easier to identify which group it belongs to, and support folding or expanding the group.Optimizing the display of the token group is very important. You can refer to the typesetting layout of the Figma layer.The Figma layer structure, the vision is very clear.
<img width="180" alt="image" src="https://user-images.githubusercontent.com/46061868/175559324-e38d6e91-3ff3-42bd-b363-cc2679718b17.png">

**Comment by six7** [comment] 2022-07-06 11:37
This is a duplicate of #564 I believe

Duplicate of #564

**Closed by six7** 2022-07-06 11:37 UTC
