### ISSUE TITLE
(DRAFT) Non local styles not working with JSONBIN

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1089] opened 2022-07-26 16:03 UTC
**Describe the bug**
Non local styles not working with JSONBIN

**To Reproduce**
Still unclear how to reproduce > seems to happen sometimes.

**Expected behavior**

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment] 2022-07-26 22:20
Is this a placeholder?

**Comment by rbosker** [comment] 2022-07-27 09:00
this ticket needs to be enriched @MightyDevKnight yesterday got a report of this issue. I will keep an eye on this story to get the reproduction steps in place.

**Comment by six7** [comment] 2022-08-02 07:18
I can't reproduce this one, tried on the `next` branch.

**Comment by six7** [comment] 2022-08-13 21:44
Closing this, lets reopen another one if this issue should reappear

**Closed by six7** 2022-08-13 21:44 UTC
